### ISSUE TITLE
Remove utm_ parameters from URL

### ISSUE THREAD

**Issue by rasendubi** [heutagogy/heutagogy-backend#103]
They clutter the URL and I believe they are safe to remove. (I currently do this manually for all my bookmarks.)

Example:
```
?utm_source=pocket&utm_medium=email&utm_campaign=pockethits
```

**Comment by drets** [comment]
Is issue specific only to pocket?

**Comment by rasendubi** [comment]
No, it's not. These tags are [Google Analytics campaign parameter](https://support.google.com/analytics/answer/1033863?hl=en). I see hundreds of websites inserting them.

**Comment by drets** [comment]
OK, more generic solution would be to allow user set the URL filtering options from frontend or extension.
