### ISSUE TITLE
It should be possible to create/register as much users as we can

### ISSUE THREAD

**Issue by Faradey27** [heutagogy/heutagogy-backend#12]
Problem: I want to be able to register my account and get all saved data that related to my account, I also do not want anyone else saw my saved data.

Solution: Implement authentication logic(api) which will give ability to register new user and to logic for old users. Always check that user receive only his data.

Related: https://github.com/heutagogy/heutagogy-backend/issues/2

**Comment by rasendubi** [comment]
Basically, the problem statement doesn't describe the problem but rather a solution in other words.

The actual problem is sharing the server. We would like users to share servers, so they have an ability to reuse other people's servers and don't set up their own.

**Comment by rasendubi** [comment]
I would also split supporting multiple users and registration process. i.e., add multiple user support in this issue and work on user registration in a separate one.

**Comment by Faradey27** [comment]
> Basically, the problem statement doesn't describe the problem but rather a solution in other words.

> The actual problem is sharing the server. We would like users to share servers, so they have an ability to reuse other people's servers and don't set up their own.

@rasendubi 
What you mean  sharing the server? like all clients will have servers that can communicate between each other?

i though that we will have one central server which will store data for all users

**Comment by rasendubi** [comment]
Sharing a server means you have a single server and multiple clients connecting to it. (It's not sharing user info between servers.)

**Comment by Faradey27** [comment]
@rasendubi understood =) i m thinking like front-end

**Comment by rasendubi** [comment]
This is now done. User registration is available at `/user/register`
