### ISSUE TITLE
It should be possible to register/login with google account

### ISSUE THREAD

**Issue by Faradey27** [heutagogy/heutagogy-backend#13]
Problem: I want to be able to use my google account for authentication, i don't want to enter my login and password from chrome extension if i already logged in

Solution: Implement authentication logic(api) which will give ability to register new user and to logic for old users. Always check that user receive only his data.

Related: https://github.com/heutagogy/heutagogy-backend/issues/12

**Comment by rasendubi** [comment]
This is implemented now.
