### ISSUE TITLE
Allow exporting all user data

### ISSUE THREAD

**Issue by rasendubi** [heutagogy/heutagogy-backend#22]
Problem: as a user, I don't want to be locked-in with the current service provider and want to know I can always take my data with me if I leave. I also want my data in some open format, so I know I won't lose it if the software becomes obsolete.

Solution: implement import/export feature.

**Comment by rasendubi** [comment]
Other possible solutions would be copying sqlite database, but that's now is harder as it may contain data for multiple users.

**Comment by drets** [comment]
ping @rasendubi

**Comment by rasendubi** [comment]
ok, we have an API for getting bookmarks, so it is possible to build an export tool

**Comment by drets** [comment]
We even can export bookmarks to json file on frontend (and import from json)!

**Comment by rasendubi** [comment]
see https://github.com/heutagogy/heutagogy-frontend/issues/33
