### ISSUE TITLE
“Get article object by url” endpoint

### ISSUE THREAD

**Issue by drets** [heutagogy/heutagogy-backend#73]
Problem: if google chrome extension wants to check whether the backend has specific article − it needs to poll all articles from db (it doesn't scale if the user has billion of saved articles).
Solution: add new endpoint which returns article object by url.

**Comment by rasendubi** [comment]
This should be added as a filter for `GET /api/v1/bookmarks`. Something like `GET /api/v1/bookmarks?url=<url>`.

**Comment by rasendubi** [comment]
@drets, fixed?

**Comment by drets** [comment]
@rasendubi yep, thanks!
