### ISSUE TITLE
Unknown pagination order

### ISSUE THREAD

**Issue by drets** [heutagogy/heutagogy-backend#77]
## Issue: 
order of articles returned by the server using pagination is currently unknown

## Solution: 
check how it works and change the code for returning articles in the particular order. 

Current ordering algorithm used on frontend (will be removed after adapting pagination on frontend):
```javascript
const comparator = (articleA, articleB) => {
  const timestampA = articleA.get('timestamp');
  const timestampB = articleB.get('timestamp');
  const readA = articleA.get('read');
  const readB = articleB.get('read');

  const compareDates = (momentA, momentB) => {
    if (momentA > momentB) {
      return MINUS_ONE;
    } else if (momentA < momentB) {
      return ONE;
    }

    return ZERO;
  };

  if (readA && !readB) {
    return ONE;
  } else if (!readA && readB) {
    return MINUS_ONE;
  } else if (readA && readB) {
    return compareDates(moment(readA), moment(readB));
  }

  return compareDates(moment(timestampA), moment(timestampB));
};
```
## Bonus points: 
retrieve sorted articles if a request has `sort` query param

**Comment by rasendubi** [comment]
Going to work on this next

**Comment by drets** [comment]
Fixed by https://github.com/heutagogy/heutagogy-backend/pull/82.
