### ISSUE TITLE
Categorize bookmarks

### ISSUE THREAD

**Issue by rasendubi** [heutagogy/heutagogy-backend#78]
Problem: I have many bookmarks, so I want to categorize them to better search later.

Solution: implement tags, so I can assign multiple tags to a bookmark and filter by them later. This way I can separate my flask bookmarks from emacs ones.

**Comment by drets** [comment]
Pinned: https://github.com/heutagogy/heutagogy-backend/pull/96#issuecomment-353610382

**Comment by rasendubi** [comment]
One more use case for categorization: when I read books, I like to add chapters as separate items. It would be good to be able to build a hierarchical structure of items. e.g., book series -> book -> chapter.

**Comment by drets** [comment]
Do chapters have their own URL? Does server support a hierarchical structure of items?

**Comment by rasendubi** [comment]
> Do chapters have their own URL?

Usually, yes—all chapters are placed on separate pages. Though, there is still a potential use case for tracking offline resources.

> Does server support a hierarchical structure of items?

No.

**Comment by rasendubi** [comment]
Here is a migration script to move all `@things` from title to tags field.

/cc @drets 

```python
#!/usr/bin/env python3
import json
import requests
import subprocess
import re

preview = False

username = 'rasen'
password = subprocess.run(['pass', 'heutagogy.herokuapp.com/rasen'], stdout=subprocess.PIPE).stdout.decode().strip()

host = 'https://heutagogy.herokuapp.com/api/v1'

res = requests.post(host + '/login',
                    json={'username': username, 'password': password})
if res.status_code != 200:
    print('Error logging in')
    print(res.json())
    exit(1)

token = res.json()['access_token']
# print(token)

res = requests.get(host + '/bookmarks',
                   params={'per_page': 2000},
                   headers={'Authorization': 'JWT {}'.format(token)})
if res.status_code != 200:
    print('Error getting bookmarks')
    print(res.json())
    exit(1)

bookmarks = res.json()

for b in bookmarks:
    title = b['title']
    tags = b['tags']

    newtags = re.findall("@\\S+", title)
    newtags = list(map(lambda tag: tag[1:], newtags)) + (b.get('tags', []) or [])
    newtitle = re.sub("@\\S+", "", title).strip()

    if (not newtags or tags == newtags) and title == newtitle:
        continue

    if preview:
        print('"{}" -> "{}" {}'.format(title, newtitle, newtags))
    else:
        res = requests.post(host + '/bookmarks/{}'.format(b['id']),
                            json={'title': newtitle, 'tags': newtags},
                            headers={'Authorization': 'JWT {}'.format(token)})
        print()
        print(b)
        print(res.json())
```

**Comment by rasendubi** [comment]
Ok, with both tagging and hierarchies I can close this now.
