### ISSUE TITLE
Fix registration page + add starting static page.

### ISSUE THREAD

**Issue by drets** [heutagogy/heutagogy-backend#79]
## Problem: 
![selection_043](https://cloud.githubusercontent.com/assets/6199462/22544052/7fb11924-e933-11e6-9514-55019c9f69b1.jpg)
**+** wrong redirection
## Solution:
• MyApp ⇒ Heutagogy in header
• Remove footer :question: 
• Click on “Sign in” should redirect to https://heutagogy-frontend.herokuapp.com/ :grey_question: 
• After successful registration  a user should be redirected to https://heutagogy-frontend.herokuapp.com/ :grey_question:

## Notes:
Registration form is generated by http://pythonhosted.org/Flask-User/

**Comment by rasendubi** [comment]
I would like to keep frontend and backend separated at this point. That means, redirecting to heutagogy-frontend is not ok. Especially for sign in, where backend has its own sign in for changing username/password.

An alternative solution would be implementing a simple starting page, so we redirect user there. It should include links to frontend and chrome extension, as well as back to registration page.

**Comment by drets** [comment]
## Update:
A user redirection occurs only after registration. Redirection is going to be on starting static page (aka “Getting started” page) which should be inside this repo.

**Comment by rasendubi** [comment]
@drets what's left? can this be closed?
