### ISSUE TITLE
Get title from the actual page if client doesn't provide the title of the page

### ISSUE THREAD

**Issue by drets** [heutagogy/heutagogy-backend#85]
Problem: currently mobile app may get only URL and for getting title of the page we make a request, parsing a page on mobile (it's quite heavy operation which may slow down the app)

Solution: let server handle the such case and if title is not provided − server will make a request and parse the page for getting a title.

**Comment by rasendubi** [comment]
@drets, fixed?

**Comment by drets** [comment]
@rasendubi fixed by https://github.com/heutagogy/heutagogy-backend/issues/86, thanks!
